# Laptop Price Classification

Bu projede diz üstü bilgisayarların fiyatlarını sınıflandıracak modeli geliştiriyoruz

### Keşfedici Veri Analizi

In [1]:
import pandas as pd
pd.set_option("display.max_columns", None)
import warnings
warnings.filterwarnings("ignore")
import numpy as np

In [2]:
df=pd.read_excel("data.xlsx")

In [3]:
df.head()

Bellek Hızı Cihaz Ağırlığı Ekran Boyutu Ekran Kartı Bellek Tipi  \
0    1066 MHz            NaN       10 inç                     NaN   
1    1066 MHz            NaN       10 inç                     NaN   
2    1066 MHz            NaN       10 inç                     NaN   
3    3200 MHz       1 - 2 kg     15,6 inç                   GDDR4   
4    3200 MHz       1 - 2 kg     15,6 inç                   GDDR5   

  Ekran Kartı Hafızası    Ekran Kartı Tipi Ekran Panel Tipi İşlemci Nesli  \
0                 1 GB                 NaN              IPS       1.Nesil   
1                 1 GB                 NaN              IPS       1.Nesil   
2                 1 GB                 NaN              IPS       1.Nesil   
3                 2 GB  Harici Ekran Kartı              LED     10. Nesil   
4                 2 GB  Harici Ekran Kartı              LED     10. Nesil   

  İşlemci  İşletim Sistemi Kart Okuyucu  Aydınlatma Maksimum İşlemci Hızı  \
0   1000M          Android          NaN           0              1,05 GHz   
1   1000M          Android          NaN           0              1,05 GHz   
2   1000M          Android          NaN           0              1,05 GHz   
3  1035G1  Windows 10 Home          Var           0               3,6 GHz   
4  1035G1  Windows 10 Home          Yok           0               3,6 GHz   

  Max Ekran Çözünürlüğü Parmak İzi Okuyucu Ram (Sistem Belleği)  \
0                   NaN                NaN                  NaN   
1                   NaN                NaN                  NaN   
2                   NaN                NaN                  NaN   
3           1920 x 1080                Yok                 8 GB   
4           1920 x 1080                Yok                12 GB   

  SSD Kapasitesi Ürün Modeli       Fiyat  
0           1 TB    Notebook  Çok Yüksek  
1           1 TB    Notebook  Çok Yüksek  
2           1 TB    Notebook        Orta  
3         512 GB    Notebook       Düşük  
4           1 TB    Notebook       Düşük

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 994 entries, 0 to 993
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Bellek Hızı              888 non-null    object
 1   Cihaz Ağırlığı           985 non-null    object
 2   Ekran Boyutu             994 non-null    object
 3   Ekran Kartı Bellek Tipi  884 non-null    object
 4   Ekran Kartı Hafızası     946 non-null    object
 5   Ekran Kartı Tipi         955 non-null    object
 6   Ekran Panel Tipi         994 non-null    object
 7   İşlemci Nesli            946 non-null    object
 8   İşlemci                  979 non-null    object
 9   İşletim Sistemi          994 non-null    object
 10  Kart Okuyucu             864 non-null    object
 11  Aydınlatma               994 non-null    int64 
 12  Maksimum İşlemci Hızı    950 non-null    object
 13  Max Ekran Çözünürlüğü    988 non-null    object
 14  Parmak İzi Okuyucu       886 non-null    o

In [5]:
# Hangi alanlarda boş veri var
bos=df.isnull().sum()
bos[bos>0]

Bellek Hızı                106
Cihaz Ağırlığı               9
Ekran Kartı Bellek Tipi    110
Ekran Kartı Hafızası        48
Ekran Kartı Tipi            39
İşlemci Nesli               48
İşlemci                     15
Kart Okuyucu               130
Maksimum İşlemci Hızı       44
Max Ekran Çözünürlüğü        6
Parmak İzi Okuyucu         108
Ram (Sistem Belleği)         7
SSD Kapasitesi               3
dtype: int64

In [6]:
df["Bellek Hızı"].value_counts()
# Bu alan sayıya çevrilebilir ve boş verileri en sık veri ile doldurulabilir

Bellek Hızı
3200 MHz    655
4800 MHz    100
2666 MHz     71
2400 MHz     17
2933 MHz     14
5200 MHz      6
4266 MHz      6
4267 MHz      4
1066 MHz      3
3000 MHz      3
3733 MHz      2
5500 MHz      2
2133 MHz      2
6400 MHz      1
1600 MHz      1
1866 MHz      1
Name: count, dtype: int64

In [7]:
df["Cihaz Ağırlığı"].value_counts()
# Bu alan 2 ve 4 verilerine dönüştürülebilir ve boş veriler yine en sık veri ile doldurulabilir

Cihaz Ağırlığı
1 - 2 kg        586
2 - 4 kg        303
2 kg ve Altı     95
4 kg ve Üstü      1
Name: count, dtype: int64

In [8]:
df["Ekran Boyutu"].value_counts()
# Bu alan sayıya çevrilebilir

Ekran Boyutu
15,6 inç    681
14 inç      136
16 inç       38
17,3 inç     36
16,1 inç     30
13 inç       20
14,1 inç     20
13,3 inç     15
10 inç        3
18,4 inç      3
15 inç        2
13,5 inç      2
11,6 inç      2
17 inç        2
18 inç        2
13,4 inç      1
12,3 inç      1
Name: count, dtype: int64

In [9]:
df["Ekran Kartı Bellek Tipi"].value_counts()
# Bu alan verileri gruplandırılıp dummy uygulanabilir, boş veriler Onboard ile doldurulabilir

Ekran Kartı Bellek Tipi
Onboard    529
GDDR6      289
GDDR5       45
GDDR4       12
DDR5         7
DDR3         1
GDDR6X       1
Name: count, dtype: int64

In [10]:
df["Ekran Kartı Hafızası"].value_counts()
# Bu alan verileri sayıya çevrilebilir. Paylaşımlı olanlar ve boş veriler 0 olarak değiştirilebilir

Ekran Kartı Hafızası
Paylaşımlı    597
4 GB          142
2 GB           82
6 GB           72
8 GB           37
16 GB          10
1 GB            3
12 GB           3
Name: count, dtype: int64

In [11]:
df["Ekran Kartı Tipi"].value_counts()
# Dahili:0, Harici:1, Yüksek harici:2 olarak değiştirilebilir. Boş veriler 0 olur

Ekran Kartı Tipi
Dahili Ekran Kartı                  596
Harici Ekran Kartı                  183
Yüksek Seviye Harici Ekran Kartı    176
Name: count, dtype: int64

In [12]:
df["Ekran Panel Tipi"].value_counts()
# Bu panelleri pahalı ve ucuz olarak gruplayabiliriz. Pahalı olanlar 1 diğerleri 0
# Pahalı olanlar: IPS, OLED, Liquid Retina XDR, LTPS, Mini LED
# Ucuz olanlar: TN, WVA, LED, SVA

Ekran Panel Tipi
IPS                    625
TN                     190
WVA                     80
LED                     54
OLED                    14
Liquid Retina XDR       14
SVA                     10
LTPS                     3
Mini LED                 2
Liquid Retina Ekran      2
Name: count, dtype: int64

In [13]:
df["İşlemci Nesli"].value_counts()
# Bu veriler Intel, AMD ve Apple olarak gruplandırılıp dummy yapılabilir. Boş veriler Intel ile doldurulur

İşlemci Nesli
11.Nesil          341
12.Nesil          246
5.Nesil            90
Ryzen              79
13.Nesil           53
10. Nesil          34
10.Nesil           25
4.Nesil            15
7.Nesil            13
6.Nesil            11
Apple M2 Pro        8
Apple M2            5
M2                  4
3.Nesil             3
9.Nesil             3
Apple M2 Max        3
İntel N Serisi      3
1.Nesil             3
8.Nesil             2
M2 Max              2
M2 Pro              2
Yok                 1
Name: count, dtype: int64

In [14]:
df["İşlemci"].value_counts()
# Burada çeşit çok. Eğitimden çıkarılabilir

İşlemci
1135G7          144
1255U            79
1235U            71
1165G7           68
1115G4           47
               ... 
AMD R7-5700U      1
6800HS            1
N4150             1
7Y57              1
7320U             1
Name: count, Length: 87, dtype: int64

In [15]:
df["İşletim Sistemi"].value_counts()
# Bu alan ücretli ücrestsiz olarak gruplandırılabilir. Boş veriler 0 olur

İşletim Sistemi
Yok (Free Dos)     478
Windows 11 Home    198
Windows 11 Pro     137
Windows 10 Pro      55
Windows 10 Home     47
macOS               42
Ubuntu              31
Android              3
Chrome OS            3
Name: count, dtype: int64

In [16]:
df["Kart Okuyucu"].value_counts()
# En sevdiğim. 1-0. Boş veriler çoğunluk olan 1 ile doldurulabilir

Kart Okuyucu
Var    471
Yok    393
Name: count, dtype: int64

In [17]:
df["Aydınlatma"].value_counts()
# Bu alana bir şey yapmaya gerek yok

Aydınlatma
0    752
1    242
Name: count, dtype: int64

In [18]:
df["Maksimum İşlemci Hızı"].value_counts()
# Bu alan sayıya çevrilip boşluklar ortalama veya 4,7 ile doldurulabilir

Maksimum İşlemci Hızı
4,7 GHz     226
4,2 GHz     175
4,5 GHz     108
4,4 GHz     104
4,1 GHz      53
4,3 GHz      47
5 GHz        37
4,0 GHz      22
4,6 GHz      20
4 GHz        18
2,6 GHz      16
3,4 GHz      14
2,8 GHz      14
3,5 GHz      11
4,9 GHz       9
3,6 GHz       8
3,9 GHz       7
5,6 GHz       7
5,4 GHz       6
2,4 GHz       5
3,1 GHz       5
3,8 GHz       4
3,7 GHz       4
1,05 GHz      4
4,8 GHz       4
2,5 GHz       3
1,1 GHz       3
5,2 GHz       3
5,5 Ghz       2
2,3 GHz       2
2,1 GHz       2
2 GHz         2
1,2 GHz       1
3,2 GHz       1
3 GHz         1
2,2 GHz       1
1,8 GHz       1
Name: count, dtype: int64

In [19]:
df["Max Ekran Çözünürlüğü"].value_counts()
# Bu sayılar çarpılarak piksel sayıları hesaplanabilir. Boş veriler en sık ile doldurulur

Max Ekran Çözünürlüğü
1920 x 1080    808
1366 x 768      55
2560 x 1600     42
1920 x 1200     24
1920 x 1280      9
3456 x 2234      9
3840 x 2160      6
2560 x 1440      6
2880 x 1800      4
3024 x 1964      4
2520 x 1680      3
3072 x 1920      3
1921 x 1080      3
1926 x 1080      2
1933 x 1080      2
3840 x 2400      2
1924 x 1080      2
2880 x 1864      2
1922 x 1080      1
2880 x 1620      1
Name: count, dtype: int64

In [20]:
df["Parmak İzi Okuyucu"].value_counts()
# Var:1, Yok:0, Boş veriler 0 ile doldurulur

Parmak İzi Okuyucu
Yok    692
Var    194
Name: count, dtype: int64

In [21]:
df["Ram (Sistem Belleği)"].value_counts()
# Sayıya çevrilip boş veriler 16 ile doldurulabilir

Ram (Sistem Belleği)
16 GB     415
8 GB      280
32 GB     150
4 GB       47
64 GB      29
12 GB      26
24 GB      21
20 GB       7
40 GB       7
36 GB       3
8 GB        1
128 GB      1
Name: count, dtype: int64

In [22]:
df["SSD Kapasitesi"].value_counts()
# Sayıya çevrilip boşlar 0 ile doldurulabilir

SSD Kapasitesi
512 GB    434
1 TB      252
256 GB    187
2 TB       40
500 GB     39
0 GB       16
128 GB     12
120 GB      6
4 TB        2
250 GB      1
 0 GB       1
64 GB       1
Name: count, dtype: int64

In [23]:
df["Ürün Modeli"].value_counts()
# Dummy yapılabilir

Ürün Modeli
Notebook               735
Oyun Bilgisayarları    235
İkisi Bir Arada         13
Ultrabook               11
Name: count, dtype: int64

In [24]:
df["Fiyat"].value_counts()
# Fiyat 1-5 arası puanlanabilir

Fiyat
Düşük         463
Orta          226
Yüksek        110
Çok Düşük     102
Çok Yüksek     93
Name: count, dtype: int64

### Veri Ön İşleme Fonksiyonu

In [25]:
def prep(df):
    df['Bellek Hızı'] = df['Bellek Hızı'].str.replace(' MHz', '').astype(float)
    df['Bellek Hızı'] = df['Bellek Hızı'].fillna(df['Bellek Hızı'].mode()[0])
    d={"1 - 2 kg":2, "2 kg ve Altı":2, "2 - 4 kg":4, "4 kg ve Üstü":4}
    df["Cihaz Ağırlığı"]=df["Cihaz Ağırlığı"].map(d)
    df['Cihaz Ağırlığı'] = df['Cihaz Ağırlığı'].fillna(2)
    df["Ekran Boyutu"] = df["Ekran Boyutu"].str.replace(" inç", "").str.replace(",", ".").astype(float)
    df["Ekran Kartı Bellek Tipi"] = df["Ekran Kartı Bellek Tipi"].fillna(df["Ekran Kartı Bellek Tipi"].mode()[0])
    df["Ekran Kartı Hafızası"] = df["Ekran Kartı Hafızası"].fillna("0")
    df["Ekran Kartı Hafızası"] = df["Ekran Kartı Hafızası"].str.replace(" GB", "").str.replace("Paylaşımlı", "0").astype(int)
    d={"Dahili Ekran Kartı":0, "Harici Ekran Kartı":1, "Yüksek Seviye Harici Ekran Kartı":2}
    df["Ekran Kartı Tipi"]=df["Ekran Kartı Tipi"].map(d)
    df["Ekran Kartı Tipi"] = df["Ekran Kartı Tipi"].fillna(0)
    d={"IPS":1, "OLED":1, "Liquid Retina XDR":1, "Liquid Retina Ekran":1, "LTPS":1, "Mini LED":1}
    df["Ekran Panel Tipi"]=df["Ekran Panel Tipi"].map(lambda x: d.get(x, 0))
    df['İşlemci Nesli'] = df['İşlemci Nesli'].fillna("Intel")
    df['İşlemci Nesli'] = df['İşlemci Nesli'].map(lambda x: 'AMD' if x == 'Ryzen' else 'Apple' if 'M2' in x else 'Intel')
    df.drop("İşlemci", axis=1, inplace=True)
    df['İşletim Sistemi'] = df['İşletim Sistemi'].map(lambda x: 1 if ("Windows" in x) or ("macOS" in x) else 0)
    df['Kart Okuyucu'] = np.where(df['Kart Okuyucu'] == 'Var', 1, 0)
    df["Maksimum İşlemci Hızı"] = df["Maksimum İşlemci Hızı"].fillna("4,7")
    df["Maksimum İşlemci Hızı"] = df["Maksimum İşlemci Hızı"].str.replace(" GHz", "").str.replace(" Ghz", "").str.replace(",",".").astype(float)
    df['Max Ekran Çözünürlüğü'] = df['Max Ekran Çözünürlüğü'].fillna("1920 x 1080")
    df['Max Ekran Çözünürlüğü'] = df['Max Ekran Çözünürlüğü'].apply(lambda x: eval(x.replace(' x ', '*')))/1000000
    df['Parmak İzi Okuyucu'] = np.where(df['Parmak İzi Okuyucu'] == 'Var', 1, 0)
    df["Ram (Sistem Belleği)"] = df["Ram (Sistem Belleği)"].fillna(df["Ram (Sistem Belleği)"].mode()[0])
    df["Ram (Sistem Belleği)"] = df["Ram (Sistem Belleği)"].str.replace("GB", "").astype(int)
    df['SSD Kapasitesi'] = df['SSD Kapasitesi'].str.strip()
    df["SSD Kapasitesi"] = df["SSD Kapasitesi"].fillna("0 TB")
    df['SSD Kapasitesi'] = df['SSD Kapasitesi'].map(lambda x: float(x.split(' ')[0]) 
                                                    if 'TB' in x else float(x.split(' ')[0]) / 1024)
    d={'Çok Düşük': 0, 'Düşük': 1, 'Orta': 2, 'Yüksek': 3,  'Çok Yüksek': 4}
    df["Fiyat"]=df["Fiyat"].map(d)

In [26]:
prep(df)
df.head()

Bellek Hızı  Cihaz Ağırlığı  Ekran Boyutu Ekran Kartı Bellek Tipi  \
0       1066.0             2.0          10.0                 Onboard   
1       1066.0             2.0          10.0                 Onboard   
2       1066.0             2.0          10.0                 Onboard   
3       3200.0             2.0          15.6                   GDDR4   
4       3200.0             2.0          15.6                   GDDR5   

   Ekran Kartı Hafızası  Ekran Kartı Tipi  Ekran Panel Tipi İşlemci Nesli  \
0                     1               0.0                 1         Intel   
1                     1               0.0                 1         Intel   
2                     1               0.0                 1         Intel   
3                     2               1.0                 0         Intel   
4                     2               1.0                 0         Intel   

   İşletim Sistemi  Kart Okuyucu  Aydınlatma  Maksimum İşlemci Hızı  \
0                0             0           0                   1.05   
1                0             0           0                   1.05   
2                0             0           0                   1.05   
3                1             1           0                   3.60   
4                1             0           0                   3.60   

   Max Ekran Çözünürlüğü  Parmak İzi Okuyucu  Ram (Sistem Belleği)  \
0                 2.0736                   0                    16   
1                 2.0736                   0                    16   
2                 2.0736                   0                    16   
3                 2.0736                   0                     8   
4                 2.0736                   0                    12   

   SSD Kapasitesi Ürün Modeli  Fiyat  
0             1.0    Notebook      4  
1             1.0    Notebook      4  
2             1.0    Notebook      2  
3             0.5    Notebook      1  
4             1.0    Notebook      1

### Sınıflandırma Modeli

In [36]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

g = GaussianNB()
b = BernoulliNB()
l = LogisticRegression()
d = DecisionTreeClassifier()
r = RandomForestClassifier()
gb= GradientBoostingClassifier()
kn= KNeighborsClassifier()

def algo_test(x, y):
    modeller=[g, b, l, d, r, gb, kn]
    isimler=["GaussianNB", "BernoulliNB", "LogisticRegression", "DecisionTreeClassifier", 
             "RandomForestClassifier", "GradientBoostingClassifier", "KNeighborsClassifier"]

    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.2, random_state = 42)
    
    accuracy = []
    precision = []
    recall = []
    f1 = []
    mdl=[]

    print("Veriler hazır modeller deneniyor")
    for model in modeller:
        print(model, " modeli eğitiliyor!..")
        model=model.fit(x_train,y_train)
        tahmin=model.predict(np.array(x_test) if model==kn else x_test)
        mdl.append(model)
        accuracy.append(accuracy_score(y_test, tahmin))
        precision.append(precision_score(y_test, tahmin, average='macro'))
        recall.append(recall_score(y_test, tahmin, average='macro'))
        f1.append(f1_score(y_test, tahmin, average='macro'))
        print(confusion_matrix(y_test, tahmin))

    print("Eğitim tamamlandı.")
    
    metrics=pd.DataFrame(columns=["Accuracy", "Precision", "Recall", "F1", "Model"], index=isimler)
    metrics["Accuracy"] = accuracy
    metrics["Precision"] = precision  
    metrics["Recall"] = recall
    metrics["F1"] = f1
    metrics["Model"]=mdl

    metrics.sort_values("F1", ascending=False, inplace=True)

    print("En başarılı model: ", metrics.iloc[0].name)
    model=metrics.iloc[0,-1]
    tahmin=model.predict(np.array(x_test) if model==kn else x_test)
    print("Confusion Matrix:")
    print(confusion_matrix(tahmin, y_test))
    print("classification Report:")
    print(classification_report(tahmin, y_test))
    print("Diğer Modeller:")
    
    return metrics.drop("Model", axis=1)

In [44]:
x=df.drop(["Fiyat"], axis=1)
y=df[["Fiyat"]]

x=pd.get_dummies(x, drop_first=True)
x.shape, y.shape

((994, 25), (994, 1))

In [37]:
algo_test(x,y)

Veriler hazır modeller deneniyor
GaussianNB()  modeli eğitiliyor!..
[[18  1  1  0  0]
 [32 33 22  1  0]
 [ 2 10 32  0  3]
 [ 2  2 21  3  1]
 [ 0  0  2  2 11]]
BernoulliNB()  modeli eğitiliyor!..
[[ 6 14  0  0  0]
 [ 3 73 10  1  1]
 [ 1 25 13  7  1]
 [ 0  5 18  6  0]
 [ 0  2  3  3  7]]
LogisticRegression()  modeli eğitiliyor!..
[[ 3 17  0  0  0]
 [ 2 80  6  0  0]
 [ 1 31 13  0  2]
 [ 1  7 17  0  4]
 [ 0  7  1  0  7]]
DecisionTreeClassifier()  modeli eğitiliyor!..
[[15  5  0  0  0]
 [ 0 82  4  0  2]
 [ 0 15 29  3  0]
 [ 0  1  7 18  3]
 [ 0  0  0  1 14]]
RandomForestClassifier()  modeli eğitiliyor!..
[[18  2  0  0  0]
 [ 3 81  4  0  0]
 [ 0 16 30  1  0]
 [ 0  2  7 19  1]
 [ 0  0  0  1 14]]
GradientBoostingClassifier()  modeli eğitiliyor!..
[[18  2  0  0  0]
 [ 0 83  5  0  0]
 [ 0 22 23  2  0]
 [ 0  2  7 17  3]
 [ 0  0  1  1 13]]
KNeighborsClassifier()  modeli eğitiliyor!..
[[11  8  1  0  0]
 [ 4 83  1  0  0]
 [ 0 22 23  2  0]
 [ 0  8 10 10  1]
 [ 0  0  2  1 12]]
Eğitim tamamlandı.
En başa

Accuracy  Precision    Recall        F1
RandomForestClassifier      0.814070   0.845785  0.809452  0.822069
DecisionTreeClassifier      0.793970   0.815228  0.770572  0.782372
GradientBoostingClassifier  0.773869   0.812571  0.757083  0.775362
KNeighborsClassifier        0.698492   0.746643  0.625474  0.660756
GaussianNB                  0.487437   0.538863  0.558527  0.479157
BernoulliNB                 0.527638   0.527924  0.415941  0.447046
LogisticRegression          0.517588   0.376353  0.360471  0.345480

In [38]:
# En başarılı model ile yeniden eğitelim
rf=RandomForestClassifier()

In [39]:
model = rf.fit(x,y)

In [41]:
import pickle
# Modeli kaydedelim
pickle.dump(model, open('LaptopPriceClass.pkl', 'wb'))

# Modeli okuyalım
LPCmodel = pickle.load(open('LaptopPriceClass.pkl', 'rb'))

### Test Verisini Deneyelim

In [42]:
df_test=pd.read_excel("test.xlsx")
# Ön işleme basamaklarını test verisi için de çalıştıralım
prep(df_test)
df_test.head()

Bellek Hızı  Cihaz Ağırlığı  Ekran Boyutu Ekran Kartı Bellek Tipi  \
0       3200.0               2          15.6                   GDDR6   
1       3200.0               2          14.1                 Onboard   
2       3200.0               2          15.6                 Onboard   
3       3200.0               2          15.6                 Onboard   
4       2400.0               2          15.6                 Onboard   

   Ekran Kartı Hafızası  Ekran Kartı Tipi  Ekran Panel Tipi İşlemci Nesli  \
0                     6                 2                 0         Intel   
1                     0                 0                 1         Intel   
2                     0                 0                 0           AMD   
3                     0                 0                 1         Intel   
4                     0                 0                 0         Intel   

   İşletim Sistemi  Kart Okuyucu  Aydınlatma  Maksimum İşlemci Hızı  \
0                0             0           1                    4.4   
1                0             1           0                    4.7   
2                0             1           0                    4.3   
3                1             1           0                    4.7   
4                0             1           0                    2.6   

   Max Ekran Çözünürlüğü  Parmak İzi Okuyucu  Ram (Sistem Belleği)  \
0               2.073600                   0                     8   
1               2.073600                   1                    16   
2               2.073600                   0                     8   
3               2.073600                   0                     8   
4               1.049088                   0                     4   

   SSD Kapasitesi          Ürün Modeli  Fiyat  
0             0.5  Oyun Bilgisayarları      2  
1             0.5             Notebook      1  
2             0.5             Notebook      0  
3             2.0             Notebook      2  
4             0.0             Notebook      0

In [45]:
x_test=df_test.drop(["Fiyat"], axis=1)
y_test=df_test[["Fiyat"]]

x_test=pd.get_dummies(x_test, drop_first=True)
x_test.shape, y_test.shape

((249, 23), (249, 1))

In [47]:
# Sütunlarda eşleşmeyen var
eksikler = list(set(x.columns) - set(x_test.columns))
eksikler

['İşlemci Nesli_Apple', 'Ürün Modeli_Ultrabook']

In [50]:
# Eksik alanları ekleyip değerleri False yapalım
for column in eksikler:
    x_test[column] = False

In [53]:
# Sütun sırasını dengeleyelim
x_test = x_test[x.columns]

In [51]:
x_test.shape, y_test.shape

((249, 25), (249, 1))

In [54]:
# Test verisini tahmin edelim
tahmin = LPCmodel.predict(x_test)

In [55]:
accuracy_score(y_test, tahmin)

0.7791164658634538

In [56]:
confusion_matrix(y_test, tahmin)

array([[12, 11,  0,  0,  0],
       [ 2, 98, 15,  1,  0],
       [ 0,  7, 46,  5,  0],
       [ 0,  0,  4, 23,  1],
       [ 0,  0,  0,  9, 15]])

In [59]:
print(classification_report(y_test, tahmin))

              precision    recall  f1-score   support

           0       0.86      0.52      0.65        23
           1       0.84      0.84      0.84       116
           2       0.71      0.79      0.75        58
           3       0.61      0.82      0.70        28
           4       0.94      0.62      0.75        24

    accuracy                           0.78       249
   macro avg       0.79      0.72      0.74       249
weighted avg       0.80      0.78      0.78       249

